al:
  vacancies:
  - chamber: lower
    district: 52
    vacant_until: 2025-01-01
az:
  vacancies:
  - chamber: lower
    district: 4
    vacant_until: 2025-01-01
ca:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2025-01-01
ma:
  vacancies:
  - chamber: lower
    district: '6th Plymouth'
    vacant_until: 2025-01-01
me:
  vacancies:
  - chamber: lower
    district: 14
    vacant_until: 2025-01-01
  - chamber: lower
    district: 51
    vacant_until: 2025-01-01
  - chamber: lower
    district: 79
    vacant_until: 2025-01-01
md:
  vacancies:
  - chamber: lower
    district: 16
    vacant_until: 2025-01-01
mi:
  vacancies:
  - chamber: lower
    district: 13
    vacant_until: 2025-01-01
  - chamber: lower
    district: 25
    vacant_until: 2025-01-01
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-01-01
mn:
  vacancies:
  - chamber: upper
    district: 45
    vacant_until: 2025-01-01
  - chamber: lower
    district: 50A
    vacant_until: 2025-01-01
nh:
  vacancies:
  - chamber: lower
    district: Rockingham 21
    vacant_until: 2025-01-01
  - chamber: lower
    district: Grafton 12
    vacant_until: 2025-01-01
  - chamber: lower
    district: Hillsborough 2
    vacant_until: 2025-01-01
nv:
  vacancies:
    - chamber: upper
      district: 18
      vacant_until: 2025-01-01
    - chamber: lower
      district: 7
      vacant_until: 2025-01-01
    - chamber: lower
      district: 10
      vacant_until: 2025-01-01
ny:
  vacancies:
  - chamber: upper
    district: 63
    vacant_until: 2025-01-01
pa:
  vacancies:
  - chamber: lower
    district: 139
    vacant_until: 2025-01-01
pr:
  vacancies:
  - chamber: lower
    district: 29
    vacant_until: 2025-01-01
ri:
  vacancies:
  - chamber: upper
    district: 25
    vacant_until: 2025-01-01
wi:
  vacancies:
  - chamber: upper
    district: 4
    vacant_until: 2025-01-01
